# Generated by Django 3.2 on 2021-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210409_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.ImageField(default='https://place-hold.it/100x60', height_field='height_field', upload_to='speciality_images', width_field='width_field'),
        ),
    ]
